# Generated by Django 5.2.7 on 2025-10-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data_pedido',
            field=models.DateField(verbose_name=models.DateField(auto_now_add=True)),
        ),
    ]
