# Generated by Django 5.2.4 on 2025-12-17 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_situacao_remove_pedido_taxa_entrega_endereco_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='situacao_pedido',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.situacao'),
            preserve_default=False,
        ),
    ]
