# Generated by Django 5.2.7 on 2025-11-04 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_pedido_data_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
