# Generated by Django 5.2.7 on 2025-11-18 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_usuario'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
