# Generated by Django 5.2.7 on 2025-11-19 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_delete_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='produto',
            name='descricao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.categoria'),
        ),
    ]
